### ISSUE TITLE
[PRAISE] Super! Exactly what i need!

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#1]
Thank you very much for this lib! 
It fully suitable for my project now.

Only one question:
How to be sure that init() method of entry point of the app call after init() methods of all sceen.script?
Now I found way that it works good, but for me it's looks like random.

**Comment by subsoap** [comment]
For the init issue I added a check to make sure the target screen has had time to add itself which should be a long enough time for initial entrypoint but in theory if you load multiple initial screens it may still be a problem.

https://github.com/britzl/monarch/pull/5

**Comment by britzl** [comment]
Thanks guys!
