### ISSUE TITLE
Popup above popup

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#10]
I have a lot of cases where I need to show popup above other popup.
For example:
- I show WinPopup, and this popup have possability to show ads for multiply of reward. ADS can return some error like "has no connection" or "ads isn't avaliable now";
- some confirmation popup like "are you sure? Yes No" and so on...

What do you think about this possibility?

**Comment by Grisgram** [comment]
I second this. Quite common use case.

**Comment by britzl** [comment]
Hmm, good point. Monarch should be able to support this. I'll need to figure out how to best solve this.

**Comment by britzl** [comment]
Fixed in 2.1 (https://github.com/britzl/monarch/releases/tag/2.1)
