### ISSUE TITLE
Applying transitions between screens

### ISSUE THREAD

**Issue by baochungit** [britzl/monarch#103]
I have 2 screens, each screen (collection) has many game objects on it. I want to switch between screens with a fade-in transition. Looking at the example I see that it seems the transitions only work on GUI nodes however screens in my knowledge are not only for GUI stuff. So can we have transition effects on the whole screen rather than GUI component?

(Sorry but I don't know a place for this kind of question. Feel free to close it if not suitable)

**Comment by britzl** [comment]
Hi @baochungit. Sure, you can do whatever you wish in your transition code. The examples and predefined transitions work on GUI nodes, but you can do anything in the transition.


```lua
monarch.on_transition("myscreen", function(message_id, message, sender)
	if message_id == monarch.TRANSITION.SHOW_IN then
		local to = 0
		local duration = 1.5
		local delay = 0
		-- animate tint.w (ie alpha to 0)
		go.animate("go#sprite", "tint.w", go.PLAYBACK_ONCE_FORWARD, to, go.EASING_INOUTQUAD, duration, delay, function()
			msg.post(sender, monarch.TRANSITION.DONE)
		end)
	end
end)

```

**Comment by baochungit** [comment]
Great to know that! At least I see it more flexible in usage. Thanks!
