### ISSUE TITLE
Mistake in the documentation (forgot hash function)

### ISSUE THREAD

**Issue by ApothemBill** [britzl/monarch#11]
There is a mistake in the documentation. Where it says:
```lua
monarch.show("first_screen")
```
it should be:
```lua
monarch.show(hash("first_screen"))
```
I was confused why it gave me an error at first. I only figured it out from reading the example code. The page on the Defold website https://www.defold.com/community/projects/88415/ also contains the same mistake.

**Comment by britzl** [comment]
Brilliant! Thank you for pointing this out. Fixed now.
