### ISSUE TITLE
Transaction issues when layout changes (screen rotation for example)

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#12]
I have issues with monarch transaction in game with 2 layouts (portrait and landscape), now I think how to solve that.
Would be great if monarch can handle it.

**Comment by britzl** [comment]
You mean transition and not transaction right?

What is happening more specifically with the transition when changing layout? I'm guessing that it might be starting and/or ending in the wrong position?

**Comment by AGulev** [comment]
yes, 
position of nodes are changed and wrong start posion of animations.
Video with bug here:
https://youtu.be/iviAdXGXdig
(top bar and pause menu after rotation)

**Comment by britzl** [comment]
Ok, got it! Need to detect layout change and update node positions. I'll try to look at this later this evening or tomorrow.

**Comment by britzl** [comment]
I believe I've managed to fix this in https://github.com/britzl/monarch/releases/tag/2.2.0

Please give it a try and let me know if it works in your project

**Comment by AGulev** [comment]
@britzl yes, now it works! Thank you!!!!!

How do you think is it possible to save current state after layout change? For example if I hide the panel in portrait (and transaction already finished) after that I'll change layout, my panel will be shown - current state is reset. 
How did you think, is it possable to handle on monarch side, or I have to do it in my code?

**Comment by britzl** [comment]
Good point. I've added an investigation task: https://github.com/britzl/monarch/issues/13
