### ISSUE TITLE
Investigate if screen state should be persisted to handle layout changes better

### ISSUE THREAD

**Issue by britzl** [britzl/monarch#13]
If a screen has been hidden using a transition and the layout changes the screen will be visible again. Investigate if this is something that Monarch should handle or if it should be taken care of by client code.

**Comment by britzl** [comment]
@AGulev I think I have an idea of how to solve this. Would it be possible for you to create a tiny example project that highlights this problem so I can experiment?

**Comment by AGulev** [comment]
@britzl no problem, I'll do this today later

**Comment by AGulev** [comment]
@britzl  done:
[Archive.zip](https://github.com/britzl/monarch/files/2039335/Archive.zip)

**Comment by britzl** [comment]
Ok, I think I got it. Would you mind trying this branch and see if it solves your problems: https://github.com/britzl/monarch/tree/resizefix

The example you sent me works as expected now at least.

**Comment by AGulev** [comment]
@britzl It works! Thank you!

**Comment by britzl** [comment]
Released https://github.com/britzl/monarch/releases/tag/2.4.0
