### ISSUE TITLE
Need warnings when a user uses a string instead of a hash

### ISSUE THREAD

**Issue by subsoap** [britzl/monarch#14]
monarch.show() etc. needs to assert that a type of string is not used

```
assert(type(id) == "userdata", "Monarch: You must provide screen IDs as hashes with hash()")
```

The assert warnings should also probably be modified to include "Monarch: " at the beginning so there is no confusion between extensions

**Comment by britzl** [comment]
Improved monarch so that both hashes and strings are accepted: https://github.com/britzl/monarch/releases/tag/2.3.0
