### ISSUE TITLE
How to know that transaction is done?

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#18]
How to know that transaction done (in collection that right now in transaction)? I receive only transition_show  message when transaction starts, and that's all.

**Comment by AGulev** [comment]
little explanation:
I have to start queue of actions in popup right after transaction-in of popup will be done.

**Comment by britzl** [comment]
Ah, yes, that would be a good addition!

I'm thinking of two different solutions:

Option 1 - callback

```
self.transition = transitions.create(gui.get_node("root"))
self.transition.show_in(transitions.slide_in_right, gui.EASING_OUTQUAD, 0.6, 0, function()
   print("show_in done!")
end)

```

Option 2 - message

```
function init(self)
	self.transition = transitions.create(gui.get_node("root"))
	self.transition.show_in(transitions.slide_in_right, gui.EASING_OUTQUAD, 0.6, 0)
end

function on_message(self, message_id, message, sender)
	self.transition.handle(message_id, message, sender)
	if message_id == monarch.TRANSITION.DONE and message.transition == monarch.TRANSITION.SHOW_IN then
		print("show_in done")
	end
end	

```

**Comment by AGulev** [comment]
I think option with a message would be great. It will be easier to wrap using  ludobits.flow.

**Comment by britzl** [comment]
Fixed in https://github.com/britzl/monarch/releases/tag/2.5.0

**Comment by AGulev** [comment]
Thank you!
