### ISSUE TITLE
Transaction constants in monarch.lua

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#2]
I want to use monarch transactions handly.
For example I want to hide game menu when show popup. But it isn't convinient to write by hands hash("transition_show_out").
I think better will be add this hashes as constants to monarch.lua and use them. Something like :
M.TRANSACTION_SHOW_OUT = hash("transition_show_out")
M.TRANSACTION_SHOW_IN = hash("transition_show_in")
and so on

Then would be great to add monarch.lua module to gui.lua for using these constants.

What do you think? (I already did this in my local copy, and I can make pull request if you do not mind)

**Comment by AGulev** [comment]
@britzl  https://github.com/AGulev/monarch/commit/de2fa9c4e2379158d0ed250050516810b6b908e4

**Comment by AGulev** [comment]
Here is this changes https://github.com/britzl/monarch/pull/3
and new type of transaction

**Comment by britzl** [comment]
Thanks! I've merged your PR.
