### ISSUE TITLE
Bug when you try to re-open popup before  it was close

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#22]
If I open popup, then closing it and open again when back_out transaction still in progress I have a bug with this popup (btns reaction works only once and close btn didn't work)

easy to reproduce if you setup monarch.show() for popup to hardware android btn or to WINDOW_EVENT_FOCUS_LOST event

but btn on bkg screen and slow back_out will be fine too

**Comment by AGulev** [comment]
Yes, I understand that I shouldn't interact with monarch when it's in transition. But I think I need some instruments for prevent this.
For example for now I have input focus even when transaction in progress and would be great to have one (or both) options:
1. Remove focus while transaction
2. monarch.is_in_transaction flag for lock new interaction with monarch manualy

**Comment by britzl** [comment]
But what if Monarch ignores calls to monarch.show() and back() while it is busy switching screens? A call to monarch.show()/back() could return immediately, optionally also returning false.

Another option would be to queue up navigation requests but I'm not sure about that either. Simply preventing interaction while Monarch is busy seems like a good and straight forward solution to the problem?

**Comment by AGulev** [comment]
> But what if Monarch ignores calls to monarch.show() and back() while it is busy switching screens? A call to monarch.show()/back() could return immediately, optionally also returning false.

yes, it will be good solution in my case.
