### ISSUE TITLE
Zero timetep does not apply

### ISSUE THREAD

**Issue by CyTheRabbit** [britzl/monarch#27]
If try setting `timestep_below_popup` to some value from 0 to 1, it could not work because of `mode = 0` sent in message `set_time_step`.
*Solution:* select mode depending on tilmestep value.

**Comment by britzl** [comment]
Why doesn't it work? Setting timestep to 0 will pause the collection completely. A value of 0.5 will reduce speed to 50% (dt becomes 1/120). The discrete mode isn't really useful other than for debug right?

NOTE: You should set the timesteo on the screen that is below the popup, not on the popup screen.

**Comment by CyTheRabbit** [comment]
Oh, I see, `tilmestep_below_popup` should be set on screen that **is** below popup, not on popup itself.
Sorry, should read documentation more carefully. 😅
