### ISSUE TITLE
Is load_async being used?

### ISSUE THREAD

**Issue by subsoap** [britzl/monarch#31]
https://www.defold.com/manuals/collection-proxy/

https://github.com/britzl/monarch/search?q=load&unscoped_q=load

I'm noticing in a project music glitches when switch screens, is load_async being used? It looks like "async_load" is being sent instead of "load_async"

https://github.com/britzl/monarch/search?q=async&unscoped_q=async

**Comment by subsoap** [comment]
Looks like the docs have it wrong somewhere https://www.defold.com/ref/collectionproxy/#async_load

**Comment by subsoap** [comment]
load_async is wrong, docs have it wrong, Monarch is doing it properly.

**Comment by britzl** [comment]
Yes, collection proxy manual is wrong. Monarch and Defold API reference is correct.
