### ISSUE TITLE
Dont unload screen

### ISSUE THREAD

**Issue by Insality** [britzl/monarch#33]
There is way, to do not unload some screens?
For now I should call preload on some windows, after it closes (For example, shop window, cause it shows often, and I want to instant feedback)

Dont know, possible or not it to implement this

**Comment by britzl** [comment]
It's currently not possible that is true, but perhaps there should be a setting per screen to not unload it and instead only disable the screen.

**Comment by Insality** [comment]
AGulev give me the advice to use factory in this case. It probably can solve my problem
But will be differents in sockets of collections, need to refactor some code to migrate to factories

Perhaps, solution with disable instead unload can be useful in some cases (and in my case too)

**Comment by britzl** [comment]
I've added support for a Preload property that can be set on a screen to always keep its resources in memory.

https://github.com/britzl/monarch/releases/tag/2.16.0
