### ISSUE TITLE
What is difference between Loaded through collection proxies and created through collection factories?

### ISSUE THREAD

**Issue by takaaptech** [britzl/monarch#38]
Hi @britzl 
I just new to Defold and still reading some basic theory building blocks
In monarch I see:
Monarch screens are created in individual collections and either loaded through collection proxies or created through collection factories.
Could you please take some notes,  best practice when to using "collection proxies" and when to using "collection factories" for creating the screen? Can you give me some example or case in a real game,  when and why using that?
Thank so much!

**Comment by britzl** [comment]
A collection factory can be used to spawn multiple instances of the same collection. A collection factory can be flagged as dynamically loaded which means that the resources used by the collection won't be loaded until the first instance is spawned.

A collection proxy can load a single instance of a collection. The resources used by the collection will be loaded when the proxy loads the collection. A collection loaded via a collection proxy will generate a separate physics world for the contents of the collection. Collision objects from two different worlds will not be able to interact. Also, you are not able to access game object properties (position, scale etc) for a game object from another collection.

So those are generic differences that have nothing to do with Monarch. In the case of Monarch I would say that it doesn't really matter much if you use collection proxies or factories for your screens and popups.

I would recommend that you start with screens and popups in collections loaded using collection proxies. It is easy to change from proxies to factories and vice versa should you feel the need to later on.

**Comment by takaaptech** [comment]
Thank you very much!
