### ISSUE TITLE
dynamically loaded screen preload issue

### ISSUE THREAD

**Issue by qinciao** [britzl/monarch#40]
I tried to show a dynamically loaded screen while it is being preloaded, and it did not work as as expected. Maybe the preloaded coroutine for this screen is being replaced by “show_in” coroutine.

**Comment by qinciao** [comment]
And the screen coroutine did not  set nil after screen preloading complete.(in function M.preload())

**Comment by britzl** [comment]
This has been fixed in Monarch 2.17.0. The problem was that you called monarch.show() while the screen was still preloading. This is now supported. I also cleaned up some of the internals of monarch to make it more stable.
