### ISSUE TITLE
If more than one screen is shown on the same frame, only the first is shown

### ISSUE THREAD

**Issue by totebo** [britzl/monarch#43]
Took me while to realise why my game over screen didn't fire. The use case here is:

1. The game starts by a ball being fired based on an angle set by the player, and the hud is shown (preloaded)
2. The ball immediately triggers game over, because that was a BAD shot, and shows game over screen (also preloaded)

The game over screen never shows in this scenario. The workaround is to wait a frame to show the game over screen, which is fine, but thought I'd mention it because it took me a while to figure out why it's not working as expected.

**Comment by britzl** [comment]
Does monarch.show() return false? You can also do monarch.is_busy() to check if Monarch is currently busy showing a screen or not.

**Comment by totebo** [comment]
Yes, it does return false! Good to know.

**Comment by britzl** [comment]
I'm thinking that maybe a monarch.when_idle(cb) function could be added that will get invoked when Monarch isn't busy anymore. Or that monarch.show() would have a queue of requests and handle them one by one.

**Comment by totebo** [comment]
"monarch.show() would have a queue of requests and handle them one by one."

That sounds like a good option to me, then it would "just work" from the devs perspective.

**Comment by britzl** [comment]
Queue support added to branch https://github.com/britzl/monarch/tree/dev-queue

@Jerakin and @totebo would you mind trying this branch on some of your projects and let me know if anything isn't working as expected?

**Comment by britzl** [comment]
I decided to merge to master and release 3.0.0 with queue support.

https://github.com/britzl/monarch/releases/tag/3.0.0
