### ISSUE TITLE
Can't change a transaction

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#50]
Before update multiple node upgrade I had a possibility to change a transaction. 
For example, when I initialize scene I need some special set of easing/time:

```lua
self.transition = transitions.create(gui.get_node("ui"))
  .show_in(transitions.slide_out_top, gui.EASING_OUTQUAD, 0.001, 0) --immidiatly show ui on the screen
```

But later I want to change it:

```lua
self.transition.show_in(transitions.slide_in_top, gui.EASING_OUTQUAD, cfg.SCR_TRANSITION_TIME, 0) --show ui with animation when we in the game
```

I use this logic a lot in my games, would be amazing to have possibility to do that

**Comment by britzl** [comment]
Ah, I see. Yes, that second call would create a new transition for the same node. Didn't think of that. I have pushed a fix.

**Comment by AGulev** [comment]
Thank you!
