### ISSUE TITLE
2.19.0 Screens not registered

### ISSUE THREAD

**Issue by wabosh** [britzl/monarch#52]
I'm using Collection Proxies to create my screens and since ( and including) 2.19.0 it doesn't load them properly anymore, throwing errors.
`ERROR:SCRIPT: /monarch/monarch.lua:178: You must provide a collection proxy URL
stack traceback:
	[C]: in function 'assert'
	/monarch/monarch.lua:178: in function 'register_proxy'
	/monarch/screen_proxy.script:31: in function </monarch/screen_proxy.script:14>`

`ERROR:SCRIPT: /monarch/monarch.lua:226: There is no screen registered with id hash: [11422257669185781866 (unknown)]
stack traceback:
	[C]: in function 'assert'
	/monarch/monarch.lua:226: in function 'unregister'
	/monarch/screen_proxy.script:35: in function </monarch/screen_proxy.script:34>`

Last working version for me is 2.18.0.

**Comment by britzl** [comment]
Huh. Can you please provide a simple repro case so that it's easier for me to debug and verify when it is fixed?

**Comment by wabosh** [comment]
Yes, sure. I'll do that in the next few days.

**Comment by britzl** [comment]
It looks like if there's a problem with the Screen Proxy property of the screen_proxy.script. The default value is "#collectionproxy". Have you changed that?

**Comment by wabosh** [comment]
No, i left everything as it was. All my proxies still have the id 'collectionproxy' and each screen_proxy.script has '#collectionproxy' as its Screen Proxy value.

**Comment by britzl** [comment]
Ok, hmm, the [example](https://github.com/britzl/monarch/tree/master/example) in Monarch works though. Please share a repro case.

**Comment by wabosh** [comment]
Ok i just tried to replicate it with a new project and it works like a charm. So i guess it has something to do with my configuration and code. I'll stay on 2.18.0 then for now until i figure it out. But thank you very much for your support and your wonderful project :+1:
