### ISSUE TITLE
SCREEN_TRANSITION_OUT_FINISHED sent to already deleted popup

### ISSUE THREAD

**Issue by snaky-ru** [britzl/monarch#53]
I'm using a popup as a listener to its own transition messages. When I close the popup with monarch.back() I get error message:

 /monarch/monarch.lua:76: /monarch/monarch.lua:121: Could not send message 'monarch_screen_transition_out_finished' from 'main:/collection0/popup#screen_proxy' to 'popup:/popup#popup'.
stack traceback:
	[C]: in function 'assert'
	/monarch/monarch.lua:76: in function </monarch/monarch.lua:75>

I looked in the monarch code and there's screen unloads before sending messages about finishing transitions. Why so? Is it possible to send messages and then unload a screen?

**Comment by britzl** [comment]
The thought behind the transition message is that it is the first and last thing that happens. But yeah, in this case I see that it's not so good. :-)

**Comment by britzl** [comment]
Hmm, how do I reproduce the issue so that I can verify a fix?

**Comment by snaky-ru** [comment]
I wasn't able to reproduce that in a simple test project. Probably the reason is different. Sorry for misreporting.

**Comment by britzl** [comment]
Hmm, ok, well, if you do find a repro case then please let me know!
