### ISSUE TITLE
Feature request: Throw an error if trying to use a screen which is not loaded

### ISSUE THREAD

**Issue by totebo** [britzl/monarch#56]
I had forgotten to load a screen before using it. It works in the editor, of course. On Facebook Instant the game crashes without an error message when using monarch.show(screen_id).

Could errors like this create an error in the log?

**Comment by britzl** [comment]
Could you explain this a bit more? Calling monarch.show() should load the screen.

**Comment by totebo** [comment]
I mean if the collection has been excluded to be loaded at runtime, and for whatever reason it's not yet loaded when Monarch is trying to show it. On Facebook Instant.

The result if it's not loaded is that the app continues to function, but input is blocked. It took me a while to figure out why, until I realised I wasn't loading the collection.

**Comment by britzl** [comment]
I'm sorry but I still don't get how you end up in this scenario. Would it be possible for you to share an example?

**Comment by totebo** [comment]
I'm using liveupdate. Are you saying that Monarch would load the liveupdate content itself???
