### ISSUE TITLE
Monarch 3.x introduced a breaking change

### ISSUE THREAD

**Issue by Jerakin** [britzl/monarch#58]
Not sure how I should raise this issue but I upgraded to Monarch 3.x and it broke a lot of my navigation even though the change log said it wasn't a breaking change. I have not had time to investigate (and probably won't for quite some time) but I _think_ it was because that I cleared the queue.

**Comment by britzl** [comment]
Oh, ok, I'm sorry about that. I'm not really able to take action on this as it is unclear what's actually wrong. I'll close this for now. Please reopen if you figure out what's wrong.
