### ISSUE TITLE
Feature request: Replace the top of the stack instead of pushing

### ISSUE THREAD

**Issue by dapetcu21** [britzl/monarch#60]
There are situations where you want linear navigation instead of nested navigation (progressing through the story, for example). I'd add a `pop: number` field to the `options` of `monarch.show()` that pops a given number of scenes from the top of the stack before adding the new screen.

For example, `pop = 1` would be used to replace the currently shown screen at the top of the stack with another one.

What do you think of this change? If it's ok with you design-wise, I can open a PR.

**Comment by britzl** [comment]
Could the no_stack option be used?

**Comment by dapetcu21** [comment]
Not really. Using no_stack would require me to call hide, then call show. This runs the back_out transition on the prev screen, then the show_in transition on the new screen.

What I want is show_out, then show_in just like with nested navigation.

Additionally, this doesn't pop any popups that are already on the stack.

What I'm proposing would be the semantic equivalent of `window.navigator.replace()` from the Web.

**Comment by dapetcu21** [comment]
Here's another usecase: Say you have a tabbed popup on top of the stack. You could use something like `pop` or `replace()` to transtion from `/main_screen/popup_tab1` to  `/main_screen/popup_tab2`

**Comment by britzl** [comment]
Ah, yeah, ok. I like monarch.replace() to replace the top item on the stack with a new screen (and play transitions).

**Comment by dapetcu21** [comment]
Yeah, I was thinking of adding `monarch.replace()` as well and make it a shortcut for passing `pop = 1` to `show` (also makes it easier not to duplicate code). I'll write a PR in a sec
