### ISSUE TITLE
Add a FAQ

### ISSUE THREAD

**Issue by subsoap** [britzl/monarch#68]
![61f2636fc8c2ec9e9b56a4e63e3e8225c614e5f5](https://user-images.githubusercontent.com/409170/103418120-2542ed80-4b42-11eb-9449-a153abe75fd2.png)

I've seen this come up multiple times so may be worth adding the text of the error and the explanation of why it happens to a FAQ section so it shows up in search engines.

**Comment by britzl** [comment]
You mean in Monarch or in Defold?

**Comment by subsoap** [comment]
Monarch. I mean mentioning the text of this error so that it shows in Monarch's readme and is searchable as it is a common gotcha that people do not immediately realize they need to use unique internal collection names (many confuse with file names still).

**Comment by britzl** [comment]
Got it. Added an FAQ here: https://github.com/britzl/monarch#monarch-faq
