### ISSUE TITLE
Way to find out if the screen is a popup 

### ISSUE THREAD

**Issue by 546342** [britzl/monarch#69]
It would be very useful to have a method that tells whether the screen is a popup.

eg: `monarch.is_popup(screen_id)`

In my case I’m trying to show blackout under popups via separate gui component. I subscribed to monarch events via `monarch.add_listener()` but the only way to know that the screen is a popup is to compare the screen_id with the list of popups ids.

What do you think about it? 
Thanks.

**Comment by britzl** [comment]
Closed by https://github.com/britzl/monarch/pull/70
