### ISSUE TITLE
Add to asset portal

### ISSUE THREAD

**Issue by subsoap** [britzl/monarch#7]
I've been using in a few projects with no issues. Any reason not to add it to asset portal yet?

**Comment by britzl** [comment]
I've been reluctant to add it since I didn't feel it was battle proven enough. I've used it myself for a while now, and both you and Agulev are using the lib, so I guess now is the time to add it to the Asset Portal.

**Comment by britzl** [comment]
https://www.defold.com/community/projects/88415/
