### ISSUE TITLE
Can't get monarch.post to work

### ISSUE THREAD

**Issue by RaymondDuke** [britzl/monarch#71]
<img width="525" alt="monarch post - Defold Editor 2 0 2021-03-08 03-58-33" src="https://user-images.githubusercontent.com/4392457/110261802-11e15200-7fcb-11eb-8e68-2b6b62e69a43.png">

Sample project

[monarch post.zip](https://github.com/britzl/monarch/files/6098322/monarch.post.zip)

**Comment by britzl** [comment]
hello.gui_script has nested on_message functions, one within the other:

```
function on_message(self, message_id, message, sender)
    function on_message(self, message_id, message, sender)
        if message_id == hash("_testing") then
            print("post is working")
        end
    end
end
```

You are also trying to post messages without providing a message id:

```
monarch.post("hello") -- NO MESSAGE ID!

monarch.post("hello", "mymessageid") -- <-- this is how it is supposed to look

monarch.post("hello", "mymessageid", { foo = "bar" }) -- with an optional message as well
```

**Comment by RaymondDuke** [comment]
Thanks so much. Those are some simple mistakes I should have noticed!
