### ISSUE TITLE
Option to remove group/multiple screens from stack

### ISSUE THREAD

**Issue by vishalphadtare-dev** [britzl/monarch#75]
Hello,

as discussed on the Defold forum I have a feature request for Monarch,

removing a group/multiple screens of screens from the stack,
in example [Github ](https://github.com/vishalphadtare-dev/Monarch-Example/tree/Defold) I explain the requirement to option to remove multiple options,

I have Hud with multiple options button to open, [Screen A], [Screen B] [Screen C]
from the screen, I can navigate to subscreens, for example [Screen A] -> [Screen A.1] -> [Screen A.2] -> [Screen A.3] 
as hud is still available, I can still tap on Screen B Or Screen C from hud, 

once I tab on Screen B, I want to clear all the screens open from Screen A menu (Screen A, Screen A.1, Screen A.2 and Screen A.3) that is to avoid back key navigation from the new option.

This will also help clear all the multiple screens that we don't want in the unwinding of the screen stack.
Please consider this as an Improvement and feature request.

**Comment by britzl** [comment]
What should happen with the visible screens? Should A1, A2, A3 play their transitions as if doing monarch.back() multiple times until reaching the A? Or should it be an instant clear without any transitions?

**Comment by vishalphadtare-dev** [comment]
I think Top screen should be removed with the show_out transition,
all other screens can be cleared without any animation, (don't need other screens to be visible)
suppose I navigated from Screen A to-> A1 -> A2 -> A3. we can only have show_out transition to A3 and other screens can be removed directly. 
What's your thought on this?

**Comment by britzl** [comment]
@vishalphadtare-dev please give the `https://github.com/britzl/monarch/tree/dev-back-to` branch a try. There's a new `monarch.back_to(screen, data, cb)` function for you to test.

**Comment by vishalphadtare-dev** [comment]
@britzl , I tied dev-back-to branch, 
however with method ```monarch.back_to(screen, data, cb)``` it's actually looking for a screen to relaunch which is already in the stack, 
but this is not what I am looking for,  I want to launch a fresh screen and same time wanted to clear some screen from the stack. 

I have HUD with multiple navigation buttons to open screen group, [Screen A], [Screen B] [Screen C]
I want to clear screens opens from a specific group,
for example from Screen A button I navigate to Screen A1 to Screen A2 to Screen A3, and as hud is still available player tap on Screen B or Screen C, in that case, I need to clear the specific screens (that is screens A1, A2, A3) so those do not appear again in back key.

**Comment by britzl** [comment]
Isn't the hud in the screen stack in Monarch? If it is in the stack then this would work:

```
monarch.back_to("hud")
monarch.show("screenb")
```
This will navigate back to the hud and close any screens on the way (A1, A2, A3) and then immediately navigate to screen B.

Or, I guess you could also do:

```
monarch.show("hud", { clear = true}) 
monarch.show("screenb")
```

Again, this will show the "hud" and clear (ie remove) any screens on top of "hud", in this case A1, A2 and A3. And then it will show screen B.

----

If the hud isn't a screen in the stack then we need something else. Like monarch.clear() or something that clears the stack completely.

**Comment by vishalphadtare-dev** [comment]
Hud isn't a screen in the stack (not monarch screen), It handled differently with collection proxy, as I wanted to have the same hud for all screens on the [forum](https://forum.defold.com/t/monarch-common-hud-for-different-collectionfactory/68496/4) I got a suggestion to use collection proxy.

**Comment by vishalphadtare-dev** [comment]
@britzl , any update on this? please let me know in case you need any more info.

**Comment by britzl** [comment]
Sorry, no update yet. I will try to provide a solution this week. I think `monarch.clear()` is the solution we should aim for.

**Comment by britzl** [comment]
> I think `monarch.clear()` is the solution we should aim for.

A new branch with monarch.clear() is now available for testing here: https://github.com/britzl/monarch/archive/refs/heads/dev-clear.zip

**Comment by britzl** [comment]
@vishalphadtare-dev did you get a chance to try the new monarch.clear() function?

**Comment by vishalphadtare-dev** [comment]
Hello @britzl,
Apologies for the late reply, monarch.clear() is working as expected to clear all states.
However, is it possible to pass an optional list of states to clear if someone has slightly different requirements and wants to clear specific states.

**Comment by britzl** [comment]
Thank you for confirming that monarch.clear() is working.

> However, is it possible to pass an optional list of states to clear if someone has slightly different requirements and wants to clear specific states

You mean to keep some of the screens in the stack? What would be the usecase for that? It goes against the design of a stack of screens that you add or remove from.

**Comment by vishalphadtare-dev** [comment]
@britzl, 
I agree with you about its is against the design of a stack, I will update you in case I got some use case about removing specific screens, 
However, with the `monarch.clear()` I am facing a bit wired issue when I use clear function it actually shows screens while removing for fraction of seconds, I know `monarch.clear` actually back_out all screens from the stack, but the problem is all screens showed for some time.  can we do anything for this? or any way out I can try?

**Comment by britzl** [comment]
Hmm, it should only visible remove the current screen plus any pop-ups. The rest should be cleared without being shown.

**Comment by vishalphadtare-dev** [comment]
Yes, I am using popup for the screen I need to remove on the back button using `monarch.back()` , 
I tried not marking the screen as a popup (uncheck popup option) but in that case `init()` function of the bottom screen is called again when the top screen is removed using `monarch.back()`. because of init() function, it shows all the animation of the first screen again. 
how can I avoid re-initialization of the screen in that case?

**Comment by britzl** [comment]
> how can I avoid re-initialization of the screen in that case?

Not really the way Monarch is designed. Discussed here: https://forum.defold.com/t/monarch-monarch-back-calls-init-function-of-previous-screen-again/69250/5?u=britzl
