### ISSUE TITLE
Flashing/pop-in before transitions

### ISSUE THREAD

**Issue by brettmjohnson** [britzl/monarch#77]
I was trying out the Monarch 3.4.0 example and I kept seeing a single frame flashing/pop-in from the next view before it transitions in (see video at 0:11 and 0:26 - ignore cropping). Looks really useful otherwise!

Using Defold 1.2.183 on MacOS 11.4.

https://user-images.githubusercontent.com/1270551/123565806-eb5e4700-d772-11eb-96b0-4e04d20399df.mov

**Comment by britzl** [comment]
Solved by https://github.com/britzl/monarch/commit/9e81b3a3275184a5a0d909da9dbf301445fa8db6
