### ISSUE TITLE
monarch.back() callback calling twice

### ISSUE THREAD

**Issue by Dragosha** [britzl/monarch#80]
if add callback function to back() you may noticed that it called twice. But should once(?) after the previous screen is visible.
```
DEBUG:SCRIPT: show callback
2 DEBUG:SCRIPT: back callback
```
https://github.com/britzl/monarch/blob/9e81b3a3275184a5a0d909da9dbf301445fa8db6/example/basic/screen2.gui_script#L10

**Comment by Dr-Klaus** [comment]
I also ran into this problem in the last project, I confirm ;)

**Comment by britzl** [comment]
Fixed via #d3799a93ff7ed9915ebd924bd2c9cefe304c4f04
