### ISSUE TITLE
Monarch screen stacking system

### ISSUE THREAD

**Issue by Huy-Nguyen-web** [britzl/monarch#86]
Hi, I have a problem with the monarch screen stacking system, and specifically when I stack the second screen, the first screen that has been stacked earlier was gone.

This is my project file:
[BWJ.zip](https://github.com/britzl/monarch/files/8440781/BWJ.zip)

And this is my game:
[Loopformer.zip](https://github.com/britzl/monarch/files/8440807/Loopformer.zip)

Can you please check it up for me? Thank you!

**Comment by britzl** [comment]
I took a quick look and you have set your “level” (the level select) screen as a popup. You can’t stack other screens on top of a popup (unless it is another popup and you have the “Popup on Popup” checkbox toggled).

Uncheck the “Popup” checkbox on that screen and you’re good!
