### ISSUE TITLE
collection unloading / resetting the stack

### ISSUE THREAD

**Issue by dri-richard** [britzl/monarch#87]
When we finalize/unload and then reload a collection that contains Monarch screens, the screen_proxy scripts unregister themselves from Monarch, but any open screens stay in the stack.

This has affected a debug feature we added to allow QA to load a saved game at any time, because the loaded game begins with Monarch in an unexpected state. It would be great if monarch.unregister() would remove screens from the stack, because I'd like to avoid special-purpose code to prepare the game for such a reload.

As a workaround I noticed that there is now a monarch.clear() but it isn't instantaneous as it does all of the transitions as it backs out of each screen.

**Comment by britzl** [comment]
> It would be great if monarch.unregister() would remove screens from the stack

Makes sense!
