### ISSUE TITLE
Add option to monarch.preload() to keep preloaded screen loaded

### ISSUE THREAD

**Issue by MamontRussel** [britzl/monarch#88]
```
-- preload and keep screen loaded even after navigation using hide() or back() (but not after unload())
monarch.preload("some_screen", { keep_loaded = true }, cb)
```

Based on discussion on forum:
https://forum.defold.com/t/monarch-preload/71200/4

**Comment by britzl** [comment]
It seems like there's still an issue with this functionality:

https://forum.defold.com/t/monarch-preload/71200/15?u=britzl

**Comment by britzl** [comment]
Closed via https://github.com/britzl/monarch/commit/6fe59c92c43c863bcffcd1edff59cf50562ffc44
