### ISSUE TITLE
Incorrect behaviour when sliding windows

### ISSUE THREAD

**Issue by Morgerion** [britzl/monarch#90]
I want to make sliding windows like they are done in Royal Match, Toon Blast, Squad Alpha and other top-tier projects.
I tried this a few years ago on some custom version of the Monarch (2.15.0?), and it worked:

https://user-images.githubusercontent.com/7888071/227774518-b92536f6-aecf-4bbf-a7fd-4e12e96826ba.mp4

...
I have now switched that draft project to a fresh version of Monarch (3.7.0). And it's all broken!

https://user-images.githubusercontent.com/7888071/227774599-a86704e3-a1da-4340-a5ca-2690eaf27b60.mp4

Between the two versions of the project only the Monarch's version has changed.
Here is an archive of that version of Monarch that works correctly (this is a custom version based on 2.15.0): 
[monarch__.zip](https://github.com/britzl/monarch/files/11071530/monarch__.zip)
Hopefully this will help make "sliding windows support" available in the new Monarch.

**Comment by Morgerion** [comment]
It's not a gap.
If you set a long sliding time for the windows, you can see that the second window does not start sliding until the first window has finished sliding.
And we need both windows to start sliding at the same time.

**Comment by britzl** [comment]
> If you set a long sliding time for the windows, you can see that the second window does not start sliding until the first window has finished sliding.

This is actually incorrect. I found that the default transitions positioned the node that was transitioning in on the screen too far out (twice the window width):

https://github.com/britzl/monarch/commit/fe8341263a72309fabbe29d0dab521a0e16c9120

With the correct offset it works a expected:

https://user-images.githubusercontent.com/1300688/228457758-d50163f7-0918-4741-9aa1-461b08818273.mov

**Comment by Morgerion** [comment]
Thank you, the solution turned out to be completely workable!
The issue can be closed.
