### ISSUE TITLE
Malformed URLs when using nested collections

### ISSUE THREAD

**Issue by dri-richard** [britzl/monarch#95]
(release 4.1.0)

If a screen proxy is in a collection which is in another collection, then its transition_url / focus_url / receiver_url properties are malformed, and the code to detect them in monarch.lua register_proxy() won't detect them.

To reproduce:
- Create a collection file called e.g. advanced_parent in folder example/advanced
- Add advanced.collection to the new collection
- Set advanced_parent.collection as the main collection in game.project
- Set a breakpoint in init() of screen_proxy.script
- Run

<img width="479" alt="image" src="https://github.com/britzl/monarch/assets/26457985/8faa184c-b82b-496c-9a5b-0e24d37a82b6">

**Comment by britzl** [comment]
Thanks. I've solved the issue in https://github.com/britzl/monarch/commit/df2a2a62ea0424d3be79ce406a51358bd4c4a851
