### ISSUE TITLE
Transition messages are mistimed and possibly incomplete

### ISSUE THREAD

**Issue by dri-richard** [britzl/monarch#96]
When registering a listener with add_listener(url), the full set of messages is not received during transitions, and some of them are received early.

To reproduce:
- add a listener in init() of about.gui_script:
`monarch.add_listener(msg.url())`
- add logging to on_message in the same file:
```
if message.screen and message.next_screen then
	print(message_id .. " screen: " .. message.screen .. " next screen: " .. message.next_screen)
elseif message.screen and message.previous_screen then
	print(message_id .. " screen: " .. message.screen .. " prev screen: " .. message.previous_screen)
else
	print(message_id)
end
```
- Run the example and click 'ABOUT'
- Note that the following is printed immediately:
```
[monarch_screen_transition_in_finished] screen: [about] prev screen: [menu]
[monarch_screen_transition_out_started] screen: [menu] next screen: [about]
[monarch_screen_transition_out_finished] screen: [menu] next screen: [about]
```
- Click 'OK' to go back, and note that this is printed immediately:
```
[monarch_screen_transition_out_started] screen: [about] next screen: [menu]
hash: [transition_show_out]
```

Presumably, monarch_screen_transition_out_finished can't be received by [about] as it's been unloaded but perhaps it should receive  monarch_screen_transition_in_started.

**Comment by britzl** [comment]
@dri-richard could you please try this branch and let me know what you think: https://github.com/britzl/monarch/archive/refs/heads/Issue-96-transition-messages-are-inaccurate.zip

**Comment by dri-richard** [comment]
Thanks, that works as expected.
