### ISSUE TITLE
Timing change in screen becoming 'visible'

### ISSUE THREAD

**Issue by dri-richard** [britzl/monarch#98]
(we're upgrading Monarch to v4 as a background task, hence the trickle of issues. This issue relates to v4.4.1)

For some screens, we use monarch.post as part of the setup. The typical flow is that during init() the screen will message another script, and that script will in turn use monarch.post(). However these messages are no longer received as monarch.post() only works for visible screens and recent changes mean that a screen's visible field is only set at the end of its transition.

This may be considered the correct behaviour, in which case we'll find an alternative approach.

**Comment by britzl** [comment]
Hmm, yeah, it is a bit strange that you're not able to call monarch.post() until the screen is visible... Surely it would make more sense to be able to call monarch.post() as soon as the screen is initialized?
